(function(){
    'use strict';
    var M=window.AgentControlModel, store, view, state, busy=false, activeTab='leads', dialog=document.getElementById('deskDialog'), lastUid, focusedBefore;
    var month=new Date().toLocaleDateString('en-CA').slice(0,7);
    if(!/^\d{4}-\d{2}$/.test(month))month=new Date().toISOString().slice(0,7);
    function $(id){return document.getElementById(id);}
    function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
    function money(c){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:c%100?2:0}).format(c/100);}
    function usd(v){if(!/^\d+(\.\d{1,2})?$/.test(String(v)))throw new Error('Enter a USD amount with up to two decimal places.');var n=Math.round(Number(v)*100);if(!Number.isSafeInteger(n))throw new Error('Invalid amount.');return n;}
    function key(prefix){return prefix+'_'+(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'_'+Math.random().toString(36).slice(2));}
    function when(v){if(!v)return'Not recorded';var d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):v;}
    function role(id){return M.ROLES.find(function(r){return r.id===id;});}
    function pageUrl(){return location.origin==='null'?location.href:new URL('./agent-control.html',location.href).href;}
    function option(v,label,selected){return'<option value="'+esc(v)+'"'+(selected===v?' selected':'')+'>'+esc(label)+'</option>';}
    function opts(map,selected){return Object.keys(map).map(function(k){return option(k,map[k],selected);}).join('');}
    function roles(selected){return M.ROLES.map(function(r){return option(r.id,r.name,selected);}).join('');}
    function deals(selected){return option('','No linked opportunity',selected)+state.deals.map(function(d){return option(d.id,d.name,selected);}).join('');}
    function task(id){return state.tasks.find(function(t){return t.id===id;});}
    function notice(text){$('notice').textContent=text;$('notice').hidden=false;}
    function error(e){var el=dialog.open?$('dialogError'):$('notice');el.textContent=e.message||String(e);el.hidden=false;}
    function close(){dialog.close();if(focusedBefore&&document.contains(focusedBefore))focusedBefore.focus();}
    function modal(title,html,eyebrow){
        focusedBefore=document.activeElement;$('dialogTitle').textContent=title;$('dialogEyebrow').textContent=eyebrow||'REVENUE DESK';$('dialogBody').innerHTML=html;
        // Select options and prefilled textarea content must not become part of the label name.
        $('dialogBody').querySelectorAll('label').forEach(function(label){var control=label.querySelector('input,select,textarea'),name=label.firstChild.textContent.trim();if(control&&name)control.setAttribute('aria-label',name);});
        $('dialogError').hidden=true;if(!dialog.open)dialog.showModal();var first=$('dialogBody').querySelector('input:not([type=hidden]),select,textarea,button');if(first)first.focus();
    }
    function form(id,html,submit){return'<form id="'+id+'" class="ac-form">'+html+'<div class="ac-actions"><button type="button" class="ac-btn" data-action="close">Cancel</button><button class="ac-btn ac-primary" type="submit">'+esc(submit)+'</button></div></form>';}
    function bindForm(id,fn){$(id).addEventListener('submit',async function(e){e.preventDefault();if(busy)return;try{await fn(new FormData(e.currentTarget));}catch(x){error(x);}});}
    async function act(type,payload,revision){
        if(busy)throw new Error('A save is still in progress.');busy=true;
        document.querySelectorAll('#deskDialog button[type=submit]').forEach(function(b){b.disabled=true;});
        try{await store.dispatch({id:key('event'),at:new Date().toISOString(),revision:revision==null?state.revision:revision,type:type,payload:payload||{}});}
        finally{busy=false;document.querySelectorAll('#deskDialog button[type=submit]').forEach(function(b){b.disabled=false;});}
    }
    async function copy(text){
        try{if(!navigator.clipboard)throw new Error('Clipboard unavailable');await navigator.clipboard.writeText(text);notice('Copied. Paste it into Grok Bot; nothing has been sent.');}
        catch(e){modal('Copy the handoff','<p class="ac-help">Select and copy this text, then paste it into Grok Bot. Nothing has been sent.</p><textarea class="ac-copybox" id="copyFallback" readonly aria-label="Handoff text">'+esc(text)+'</textarea>');$('copyFallback').select();}
    }
    function download(text,name,type){var u=URL.createObjectURL(new Blob([text],{type:type||'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(u);},1000);}
    function empty(title,text,button,action){return'<div class="ac-empty'+(button?'':' ac-compact')+'">'+(button?'<span class="ac-number">01 / START WITH AN OUTCOME</span>':'')+'<h2>'+esc(title)+'</h2><p>'+esc(text)+'</p>'+(button?'<button class="ac-btn ac-primary" data-action="'+action+'">'+esc(button)+'</button>':'')+'</div>';}
    function connection(){
        var labels={local:'Local workspace',cloud:'Cloud register connected',connecting:'Connecting to your account',offline:'Cloud offline · changes paused',error:'Register needs attention'};
        var detail=view.mode==='local'?'Saved in this browser. Grok has not been connected.':view.mode==='cloud'?'Shared under your Proton account. Native Grok chat is separate.':view.error||'Waiting for a confirmed server connection.';
        $('connection').className='ac-connection'+(view.mode==='cloud'?' ac-cloud':'');
        $('connection').innerHTML='<span><span class="ac-indicator"></span><strong>'+labels[view.mode]+'</strong> · '+esc(detail)+'</span><button class="ac-text-btn" data-action="'+(view.mode==='local'?'signin':'setup')+'">'+(view.mode==='local'?'Sign in for cloud sync →':'Connection details →')+'</button>';
        $('pauseButton').textContent=state.paused?'Resume queue':'Pause queue';
        $('revisionLabel').textContent=(view.mode==='cloud'?'Cloud':'Local')+' register · revision '+state.revision;
    }
    function renderMetrics(){
        var m=M.metrics(state,month),pct=Math.max(0,Math.min(100,m.contribution/state.goalCents*100));
        var cards=[['Monthly contribution',money(m.contribution)+' <small>/ '+money(state.goalCents)+'</small>','Manual cash records · '+month],['Open work',String(m.open),'Drafts, handoffs and active work'],['Needs review',String(m.review),'Results awaiting a decision'],['Potential service fees',money(m.pipeline),'Open opportunities · not revenue']];
        $('metrics').innerHTML=cards.map(function(c,i){return'<div class="ac-metric"><div class="ac-metric-label">'+c[0]+'</div><div class="ac-metric-value">'+c[1]+'</div><div class="ac-metric-note">'+c[2]+'</div>'+(i===0?'<div class="ac-progress" role="progressbar" aria-label="Monthly contribution target" aria-valuemin="0" aria-valuemax="100" aria-valuenow="'+Math.round(pct)+'"><span style="width:'+pct+'%"></span></div>':'')+'</div>';}).join('');
        $('workCount').textContent=m.open;
        $('cashSummary').innerHTML='<div class="ac-cash-summary">'+[['Earned fees collected',m.earned],['Delivery + team costs',m.delivery+m.software],['Net reserved this month',m.reserve-m.release],['Available contribution',m.contribution],['Monthly target',state.goalCents]].map(function(r){return'<div><span>'+r[0]+'</span><strong>'+money(r[1])+'</strong></div>';}).join('')+'</div>';
    }
    function renderTasks(){
        var search=$('taskSearch').value.toLowerCase(),owner=$('roleFilter').value,filter=$('stateFilter').value;
        var rows=state.tasks.filter(function(t){var closed=['done','cancelled'].includes(t.status);return (!owner||t.role===owner)&&(!search||(t.title+' '+t.brief+' '+t.result+' '+t.blocker).toLowerCase().includes(search))&&(filter==='all'||filter==='review'&&t.status==='review'||filter==='closed'&&closed||filter==='open'&&!closed);});
        if(!rows.length){$('tasks').innerHTML=state.tasks.length?empty('No tasks in this view.','Try another role, status, or search.'):empty('Your next revenue starts with a clear task.','Add the four launch assignments or give a specific job to your team. Drafts stay here until you hand them off.','Add launch tasks','launch');return;}
        var rank={review:0,blocked:1,working:2,ready:3,draft:4,done:5,cancelled:6};
        rows.sort(function(a,b){return rank[a.status]-rank[b.status]||String(a.due||'9999').localeCompare(b.due||'9999');});
        $('tasks').innerHTML='<div class="ac-task-list">'+rows.map(function(t){return'<article class="ac-task"><div class="ac-task-top"><span class="ac-tag'+(t.status==='review'?' ac-tag-review':'')+'">'+M.STATUS[t.status]+'</span><span class="ac-small">'+esc(role(t.role).name)+'</span><span class="ac-task-id">'+esc(t.id.slice(0,21))+'</span></div><button class="ac-task-title" data-action="task" data-id="'+esc(t.id)+'">'+esc(t.title)+'</button><p class="ac-task-summary">'+esc(t.brief.length>200?t.brief.slice(0,200)+'…':t.brief)+'</p>'+(t.blocker?'<p class="ac-blocker">'+esc(t.blocker)+'</p>':'')+'<div class="ac-task-bottom"><span>'+(t.due?'Due '+esc(t.due):'No due date')+(t.handoffAt?' · handoff recorded':'')+'</span><div class="ac-actions">'+(!['done','cancelled'].includes(t.status)?'<button class="ac-text-btn" data-action="copy-task" data-id="'+esc(t.id)+'">Copy handoff</button>':'')+'<button class="ac-text-btn" data-action="task" data-id="'+esc(t.id)+'">'+(t.status==='review'?'Review result →':'Open task →')+'</button></div></div></article>';}).join('')+'</div>';
    }
    function renderTeam(){
        $('team').innerHTML=M.ROLES.map(function(r){var tasks=state.tasks.filter(function(t){return t.role===r.id&&!['done','cancelled'].includes(t.status);});return'<div class="ac-role"><div class="ac-role-top"><span class="ac-avatar">'+r.initials+'</span><div><h3>'+esc(r.name)+'</h3><span class="ac-small">'+tasks.length+' open task'+(tasks.length===1?'':'s')+'</span></div></div><p>'+esc(r.job)+'</p><div class="ac-actions"><button class="ac-text-btn" data-action="profile" data-id="'+r.id+'">Role & setup</button><button class="ac-text-btn" data-action="assign" data-id="'+r.id+'">Assign work +</button></div></div>';}).join('');
    }
    function renderLeads(){
        var today=new Date().toLocaleDateString('en-CA'),m=M.leadMetrics(state,today),query=$('leadSearch').value.toLowerCase(),stage=$('leadStage').value,offer=$('leadOffer').value;
        $('leadCount').textContent=m.active;
        $('leadSummary').innerHTML=[['Active accounts',m.active],['Qualified for outreach',m.qualified],['Replies / meetings',m.conversations],['Next actions due',m.due]].map(function(x){return '<div><strong>'+x[1]+'</strong><span>'+x[0]+'</span></div>';}).join('');
        var rows=(state.leads||[]).filter(function(l){return(stage==='all'||stage==='active'&&!['dnc','disqualified'].includes(l.stage)||stage===l.stage)&&(!offer||offer===l.offer)&&(!query||(l.company+' '+l.signal+' '+l.contact+' '+l.nextAction).toLowerCase().includes(query));});
        rows.sort(function(a,b){return(a.due||'9999').localeCompare(b.due||'9999');});
        if(!rows.length){$('leads').innerHTML=(state.leads||[]).length?empty('No leads in this view.','Try another stage, service, or search.'):empty('Find the reason to buy.','Start with a real account and the decision it is facing. Add the lead-gen sprint to prepare research assignments for both markets.','Add the first lead','lead');return;}
        $('leads').innerHTML='<div class="ac-task-list">'+rows.map(function(l){var active=!['dnc','disqualified'].includes(l.stage);return '<article class="ac-task ac-lead"><div class="ac-task-top"><span class="ac-tag'+(l.stage==='dnc'?' ac-tag-review':'')+'">'+M.LEAD_STAGES[l.stage]+'</span><span class="ac-small">'+M.OFFERS[l.offer]+' · '+M.CHANNELS[l.channel]+'</span></div><button class="ac-task-title" data-action="lead" data-id="'+esc(l.id)+'">'+esc(l.company)+'</button><p class="ac-task-summary">'+esc(l.signal||'Buying signal not yet researched.')+'</p><p class="ac-help">'+(l.source?'<a href="'+esc(l.source)+'" target="_blank" rel="noopener noreferrer">Signal source ↗</a> · checked '+esc(l.checked||'not recorded'):'No signal source recorded')+'</p><p class="ac-help">'+esc(l.buyer||'Buyer role unknown')+' · '+esc(l.contact||'Contact route unknown')+'</p>'+(l.lastTouch?'<p class="ac-task-summary">Last outcome · '+esc(l.lastTouch)+'<br>'+esc(l.lastNote)+'</p>':'')+'<div class="ac-task-bottom"><span>'+esc(active?(l.nextAction||'Set a next action'):'Closed to outreach')+(active&&l.due?' · '+esc(l.due)+(l.due<=today?' · DUE':''):'')+'</span><div class="ac-actions">'+(active&&l.stage!=='discovered'?'<button class="ac-text-btn" data-action="lead-draft" data-id="'+esc(l.id)+'">Draft outreach task +</button>':'')+(['replied','meeting'].includes(l.stage)?'<button class="ac-text-btn" data-action="lead-deal" data-id="'+esc(l.id)+'">Create opportunity +</button>':'')+'<button class="ac-text-btn" data-action="lead" data-id="'+esc(l.id)+'">Update lead →</button></div></div></article>';}).join('')+'</div>';
    }
    function leadForm(id){
        var l=(state.leads||[]).find(function(x){return x.id===id;})||{id:key('lead'),company:'',website:'',offer:'custom_search',channel:'direct',stage:'discovered',signal:'',source:'',checked:'',contact:'',buyer:'',nextAction:'',due:'',notes:'',lastTouch:'',lastNote:''},revision=state.revision;
        function input(label,name,type,max){return '<label>'+label+'<input name="'+name+'" type="'+(type||'text')+'"'+(max?' maxlength="'+max+'"':'')+' value="'+esc(l[name])+'"'+(['company','website'].includes(name)?' required':'')+'></label>';}
        modal(id?'Update lead':'Research a new lead',form('leadForm','<div class="ac-form-grid">'+input('Company','company','text',180)+input('Account website','website','url',1800)+'</div><div class="ac-form-grid"><label>Service to test<select name="offer">'+opts(M.OFFERS,l.offer)+'</select></label><label>Acquisition channel<select name="channel">'+opts(M.CHANNELS,l.channel)+'</select></label></div><label>Lead status<select name="stage">'+opts(M.LEAD_STAGES,l.stage)+'</select></label><p class="ac-help">Save an unresearched account as Discovered. Qualification requires evidence, a buyer role, a contact route and a dated next action. No messages are sent.</p><label>Buying signal and relevance<textarea name="signal" maxlength="2000" placeholder="What changed, when, and why might this company need this service?">'+esc(l.signal)+'</textarea></label><div class="ac-form-grid">'+input('Signal source URL','source','url',1800)+input('Evidence checked on','checked','date')+'</div><div class="ac-form-grid">'+input('Buyer role / name','buyer','text',180)+input('Public business contact route','contact','text',300)+'</div><div class="ac-form-grid">'+input('Next action','nextAction','text',1000)+input('Next action due','due','date')+'</div><hr class="ac-divider"><p class="ac-help">Record contact, reply or meeting stages only after they occur. For a booked meeting, record the booking date here and the meeting date in the next action.</p>'+input('Actual contact / outcome date','lastTouch','date')+'<label>What happened<textarea name="lastNote" maxlength="2000" placeholder="Sent message reference, actual reply, or confirmed meeting booking.">'+esc(l.lastNote)+'</textarea></label><label>Qualification notes / closure reason<textarea name="notes" maxlength="4000" placeholder="Need, timing, authority, budget and willingness to pay: mark unknowns. Give a reason for Not a fit or Do not contact.">'+esc(l.notes)+'</textarea></label><p class="ac-help">One lead per account domain and service. Do-not-contact status cannot be cleared here; it also suppresses matching contact routes across services.</p>','Save lead'));
        bindForm('leadForm',async function(f){var p={id:l.id};f.forEach(function(v,k){p[k]=v;});await act('lead.save',p,revision);close();notice('Lead saved. This recorded research or a reported outcome; no outreach was sent.');});
    }
    function renderDeals(){
        if(!state.deals.length){$('deals').innerHTML=empty('Build a pipeline of paid assignments.','Add a customer with a specific buying decision, expected service fee, and next action.','Add opportunity','deal');return;}
        $('deals').innerHTML='<div class="ac-table-wrap"><table class="ac-table"><thead><tr><th>Customer / opportunity</th><th>Stage</th><th>Proposed fee</th></tr></thead><tbody>'+state.deals.map(function(d){return'<tr><td><button class="ac-text-btn" data-action="deal" data-id="'+esc(d.id)+'">'+esc(d.name)+'</button><small>'+esc(M.OFFERS[d.offer])+'</small></td><td>'+M.STAGES[d.stage]+'</td><td class="ac-money">'+money(d.feeCents)+'</td></tr>';}).join('')+'</tbody></table></div>';
    }
    function renderCash(){
        var rows=state.entries.filter(function(e){return e.date.slice(0,7)===month;}).sort(function(a,b){return b.date.localeCompare(a.date);});
        if(!rows.length){$('cashEntries').innerHTML=empty('No cash records for this month.','Record earned fees only after collection. Keep purchase funds and undelivered deposits out of the contribution target.');return;}
        $('cashEntries').innerHTML='<div class="ac-table-wrap"><table class="ac-table"><thead><tr><th>Date / reference</th><th>Cash record</th><th>USD</th><th>Correction</th></tr></thead><tbody>'+rows.map(function(e){return'<tr'+(e.voidedAt?' class="ac-voided"':'')+'><td>'+esc(e.date)+'<small>'+esc(e.evidence)+'</small></td><td>'+esc(e.note)+'<small>'+M.KINDS[e.kind]+(e.voidedAt?' · VOIDED: '+esc(e.voidReason):'')+'</small></td><td class="ac-money">'+(['earned','release'].includes(e.kind)?'':'−')+money(e.cents)+'</td><td>'+(e.voidedAt?'Voided':'<button class="ac-text-btn" data-action="void-cash" data-id="'+esc(e.id)+'">Void</button>')+'</td></tr>';}).join('')+'</tbody></table></div>';
    }
    function renderActivity(){ $('activity').innerHTML=state.activity.length?state.activity.map(function(e){return'<div class="ac-log"><time>'+esc(when(e.at))+'</time><span>'+esc(e.message)+'</span></div>';}).join(''):empty('A clear record of the work.','Task handoffs, results, decisions and cash records will appear here.'); }
    function render(){connection();renderMetrics();renderTasks();renderTeam();renderLeads();renderDeals();renderCash();renderActivity();}
    function newTask(selected,lead){
        var revision=state.revision;
        modal('Give the team an outcome',form('taskForm','<label>Task title<input name="title" required maxlength="180" placeholder="Compare hosting for a 50-machine fleet"></label><div class="ac-form-grid"><label>Responsible role<select name="role">'+roles(selected||'revenue')+'</select></label><label>Due date<input type="date" name="due"></label></div><label>Brief, constraints and deliverable<textarea name="brief" required maxlength="9000" rows="6" placeholder="What needs to be decided, which sources to use, and what a completed result should include."></textarea></label><label>Customer opportunity<select name="dealId">'+deals('')+'</select></label><p class="ac-help">Saves a draft. It will not start a bot or send a message.</p>','Save draft'));
        if(lead){$('taskForm').elements.title.value='Draft outreach for '+lead.company;$('taskForm').elements.brief.value='Prepare an outreach draft only. Do not send. Lead ID: '+lead.id+'\nCompany: '+lead.company+' ('+lead.website+')\nService: '+M.OFFERS[lead.offer]+'\nObserved signal: '+lead.signal+'\nSource: '+lead.source+' (checked '+lead.checked+')\nBuyer: '+lead.buyer+'\nContact route: '+lead.contact+'\nNotes: '+lead.notes+'\nUse one supported observation, a concrete deliverable and a small next step. Recheck this lead and all matching do-not-contact records before any later outreach.';}
        bindForm('taskForm',async function(f){await act('task.add',{id:key('task'),title:f.get('title'),role:f.get('role'),due:f.get('due'),brief:f.get('brief'),dealId:f.get('dealId')},revision);close();notice('Draft saved. Open it to prepare the Grok handoff.');});
    }
    function openTask(id){
        var t=task(id);if(!t)return;var buttons='';
        if(['draft','blocked'].includes(t.status))buttons+='<button class="ac-btn ac-primary" data-action="ready" data-id="'+id+'">Ready for handoff</button>';
        if(t.status==='ready')buttons+='<button class="ac-btn" data-action="handed" data-id="'+id+'">Record handoff</button><button class="ac-btn ac-primary" data-action="start" data-id="'+id+'">Claim task</button>';
        if(['ready','working','blocked'].includes(t.status))buttons+='<button class="ac-btn ac-primary" data-action="result" data-id="'+id+'">Submit result</button>';
        if(t.status==='review')buttons+='<button class="ac-btn ac-primary" data-action="decision" data-id="'+id+'">Review & decide</button>';
        if(!['done','cancelled'].includes(t.status))buttons+='<button class="ac-btn" data-action="block" data-id="'+id+'">Record blocker</button><button class="ac-text-btn" data-action="cancel" data-id="'+id+'">Cancel task</button>';
        modal(t.title,'<p class="ac-help">'+esc(role(t.role).name)+' · '+esc(M.STATUS[t.status])+' · '+esc(t.id)+'</p><div class="ac-result">'+esc(t.brief)+'</div>'+(t.blocker?'<p class="ac-blocker">'+esc(t.blocker)+'</p>':'')+(t.result?'<h3>Submitted result</h3><div class="ac-result">'+esc(t.result)+'</div>':'')+(t.sources.length?'<ul class="ac-source-list">'+t.sources.map(function(s){return'<li><a href="'+esc(M.url(s))+'" target="_blank" rel="noopener noreferrer">'+esc(s)+'</a></li>';}).join('')+'</ul>':'')+(t.reviewNote?'<p class="ac-help">Review: '+esc(t.reviewNote)+'</p>':'')+'<p class="ac-help">Handoff: '+esc(when(t.handoffAt))+'<br>Work start reported: '+esc(when(t.startedAt))+'</p><hr class="ac-divider"><div class="ac-actions">'+buttons+'</div><hr class="ac-divider"><div class="ac-actions"><button class="ac-text-btn" data-action="copy-task" data-id="'+id+'">Copy handoff packet</button><button class="ac-text-btn" data-action="download-task" data-id="'+id+'">Download packet</button></div><p class="ac-help">Claims and results are recorded in Proton; they are not a live feed from Grok. Cancelling here does not interrupt a bot already working.</p>');
        dialog.dataset.recordRevision=state.revision;
    }
    function resultForm(id){
        var t=task(id),revision=state.revision;
        modal('Submit a task result',form('resultForm','<p class="ac-help">'+esc(t.title)+' · '+esc(t.id)+'</p><label>Result and remaining uncertainties<textarea name="result" rows="9" required maxlength="18000" placeholder="Paste the worker’s result. Include what was checked, what remains unknown, and the next action.">'+esc(t.result)+'</textarea></label><label>Source URLs · one per line<textarea name="sources" rows="3" placeholder="https://…">'+esc(t.sources.join('\n'))+'</textarea></label><p class="ac-help">This records a reported result and sends it to the review queue. Source links still need independent checking.</p>','Submit for review'));
        bindForm('resultForm',async function(f){await act('task.result',{id:id,result:f.get('result'),sources:f.get('sources').split(/\r?\n/).map(function(x){return x.trim();}).filter(Boolean)},revision);close();notice('Result recorded. Review it before accepting the task.');});
    }
    function decisionForm(id){
        var t=task(id),revision=state.revision;
        modal('Review the result',form('decisionForm','<p class="ac-help">'+esc(t.title)+'</p><div class="ac-result">'+esc(t.result)+'</div>'+(t.sources.length?'<ul class="ac-source-list">'+t.sources.map(function(s){return'<li><a href="'+esc(M.url(s))+'" target="_blank" rel="noopener noreferrer">'+esc(s)+'</a></li>';}).join('')+'</ul>':'<p class="ac-help">No source links were included. Check whether the deliverable needs them.</p>')+'<label>Decision<select name="decision"><option value="revise">Request revision</option><option value="accept">Accept result</option></select></label><label>Review notes<textarea name="note" required maxlength="3000" placeholder="Record the evidence checked, your decision, and any correction required."></textarea></label><p class="ac-help">Accepting completes this task. It does not authorize sending messages, purchasing, or transferring funds.</p>','Save decision'));
        bindForm('decisionForm',async function(f){await act(f.get('decision')==='accept'?'task.accept':'task.revise',{id:id,note:f.get('note')},revision);close();notice('Review decision saved.');});
    }
    function reasonForm(id,cancel){
        var revision=state.revision;
        if(cancel){modal('Cancel this task?',form('cancelForm','<p class="ac-prose">This closes the task in Proton. If a Grok bot is already working, also send it <strong>Stop now</strong> in Grok Bot.</p>','Cancel task'));bindForm('cancelForm',async function(){await act('task.cancel',{id:id},revision);close();notice('Task cancelled in Proton. Relay Stop now in Grok if work is active.');});return;}
        modal('What is blocking the task?',form('blockForm','<label>Blocker and next action<textarea name="reason" required maxlength="2000"></textarea></label>','Save blocker'));
        bindForm('blockForm',async function(f){await act('task.block',{id:id,reason:f.get('reason')},revision);close();});
    }
    function dealForm(id,lead){
        var d=state.deals.find(function(x){return x.id===id;})||{id:key('deal'),name:'',contact:'',offer:'custom_search',stage:'qualified',feeCents:null,notes:''},revision=state.revision;
        if(lead){d.name=lead.company;d.contact=lead.contact;d.offer=lead.offer;d.feeCents=['custom_search','site_review','managed_energy_hosting'].includes(lead.offer)?null:lead.offer==='quote_review'?50000:lead.offer==='brief'?200000:150000;d.notes='Lead '+lead.id+'\nSignal: '+lead.signal+'\nSource: '+lead.source+'\nBuyer qualification: '+lead.notes+'\nNext: '+lead.nextAction;}
        modal(id?'Update opportunity':'Add a customer opportunity',form('dealForm','<label>Customer / opportunity<input name="name" required maxlength="180" value="'+esc(d.name)+'" placeholder="Customer and the decision they need to make"></label><label>Contact reference<input name="contact" maxlength="300" value="'+esc(d.contact)+'" placeholder="Name, company email, or CRM reference"></label><div class="ac-form-grid"><label>Service<select name="offer">'+opts(M.OFFERS,d.offer)+'</select></label><label>Stage<select name="stage">'+opts(M.STAGES,d.stage)+'</select></label></div><label>Proposed service fee · USD<input name="fee" type="number" min="0" step="0.01" required value="'+(d.feeCents==null?'':d.feeCents/100)+'"></label><label>Buyer need and next action<textarea name="notes" maxlength="4000">'+esc(d.notes)+'</textarea></label><p class="ac-help">Scope and fees are agreed per assignment. Proposed fees are pipeline value. Record earned collections separately when payment is received.</p>','Save opportunity'));
        if(!id){var feeEdited=false,fields=$('dealForm').elements;fields.fee.addEventListener('input',function(){feeEdited=true;});fields.offer.addEventListener('change',function(){if(!feeEdited&&['custom_search','site_review','managed_energy_hosting'].includes(fields.offer.value))fields.fee.value='';});}
        bindForm('dealForm',async function(f){await act('deal.save',{id:d.id,name:f.get('name'),contact:f.get('contact'),offer:f.get('offer'),stage:f.get('stage'),feeCents:usd(f.get('fee')),notes:f.get('notes')},revision);close();});
    }
    function cashForm(){
        var revision=state.revision;
        modal('Record a cash movement',form('cashForm','<div class="ac-form-grid"><label>Type<select name="kind" id="cashKind">'+opts(M.KINDS,'earned')+'</select></label><label>Date<input type="date" name="date" required value="'+new Date().toISOString().slice(0,10)+'"></label></div><label>Amount · USD<input name="amount" type="number" min="0.01" step="0.01" required></label><label>Description<input name="note" required maxlength="1000" placeholder="Completed sourcing assignment — fee collected"></label><label>Payment or obligation reference<input name="evidence" required maxlength="1000" placeholder="Invoice / bank reference, receipt, or reserve reason"></label><label>Customer opportunity<select name="dealId">'+deals('')+'</select></label><label class="ac-checkbox" id="earnedConfirmation"><input type="checkbox" name="confirmed" required><span>I confirm this service fee has been earned and collected. It excludes hardware purchase funds, hosting deposits, and fees for undelivered work.</span></label><p class="ac-help">This is a manual operating record. It does not send an invoice, read a bank account, or move money. Entries remain in the activity history.</p>','Record cash'));
        $('cashKind').addEventListener('change',function(){var earned=this.value==='earned';$('earnedConfirmation').hidden=!earned;$('earnedConfirmation').querySelector('input').required=earned;});
        bindForm('cashForm',async function(f){await act('cash.add',{id:key('cash'),kind:f.get('kind'),date:f.get('date'),cents:usd(f.get('amount')),note:f.get('note'),evidence:f.get('evidence'),dealId:f.get('dealId'),earnedConfirmed:f.get('confirmed')==='on'},revision);close();notice('Cash record saved. Amounts are manually reported, not bank-verified.');});
    }
    function setup(selected){
        var r=selected?role(selected):null,text=r?'# '+r.name+'\n\n'+M.COMMON+'\n\n'+r.prompt+'\n\nControl center: '+pageUrl():M.kickoff(pageUrl());
        var local=/^(localhost|127\.0\.0\.1)$/.test(location.hostname)||location.protocol==='file:';
        modal(r?r.name:'Connect the Grok team','<div class="ac-prose"><p>Proton is your task, result and revenue register. Grok Bot runs the workers in its own app.</p><ol><li>First use a separate Grok/Cursor account dedicated to Proton. Then copy the setup instructions into that account to create the six roles and the <strong>Proton Revenue Desk</strong> group.</li><li>Use the published control-center URL and sign in to the intended Proton account. Check that the same register appears on both devices.</li><li>Complete one task round trip before enabling a recurring Grok routine. Alternatively, copy a handoff and paste the result back here.</li></ol><p class="ac-help">'+(local?'This preview address is local to your computer. Grok’s cloud browser needs the published HTTPS page.':'Control-center URL: '+esc(pageUrl()))+'</p><p class="ac-help">Cloud sync shares this Proton account’s data; it does not create a restricted bot account. Proton must use a different Grok/Cursor account from Stoneport: bots on one account share their cloud computer, files and signed-in sessions. Separate group names do not isolate them. Native Grok chat and approvals remain in Grok.</p></div><label class="ac-help" for="setupText">'+(r?'Role instructions':'Team setup instructions')+'</label><textarea id="setupText" class="ac-copybox" readonly>'+esc(text)+'</textarea><div class="ac-actions" style="margin-top:16px"><a class="ac-btn" href="https://x.ai/bot" target="_blank" rel="noopener noreferrer">Grok Bot website ↗</a><button class="ac-btn" id="downloadSetup">Download setup</button><button class="ac-btn ac-primary" id="copySetup">Copy instructions</button></div><hr class="ac-divider"><p class="ac-help">Connection status: '+esc(view.mode)+'. A cloud connection means the register is synchronized, not that a Grok worker is running. No native Grok API or embedded chat connection has been verified.</p>','TEAM CONNECTION');
        $('copySetup').onclick=function(){copy(text);};$('downloadSetup').onclick=function(){download(text,'proton-grok-'+(selected||'team')+'-setup.md');};
    }
    async function leadSprint(){
        var drafts=[
            {id:'sprint_miner_signals',role:'intelligence',title:'Find 20 miners with a current buying decision',brief:'Research 20 North American mining operators with a dated purchase, relocation, hosting renewal or expansion signal. Prefer original company announcements, public requests and permissioned owner referrals. A directory entry is not intent. Record source date, checked date, company domain, buyer role, public business contact route and a specific next action in the Lead Desk. Qualify up to ten for a $500 Quote & Cost Review of up to three buyer-supplied quotes. If no current signal is found, keep Discovered and explain what must be confirmed. Do not send messages or invent leads.'},
            {id:'sprint_supplier_signals',role:'intelligence',title:'Research 20 mining and energy supplier buyers',brief:'Research 20 ASIC service firms, generator distributors, gas-treatment suppliers or mining infrastructure vendors. Use their own sites and the EPA LMOP partner network to establish market fit. Seek a specific growth signal such as a new territory, product, sales role or customer-market expansion; directory membership alone is not demand. Prioritize up to ten for a $1,500 Supplier Prospect Research pilot: 25 target accounts, five account briefs and outreach drafts for one agreed market. Record verified source links and dates, buyer role, public contact route, unknowns and next action. No guaranteed meetings or sales; no outreach.'},
            {id:'sprint_outreach',role:'outreach',title:'Prepare a personalized outreach test for both offers',brief:'Use only evidence-backed active leads, rechecking do-not-contact records. Prepare ten individual drafts per offer where the research supports fit. Each draft needs one dated observation, the bounded paid deliverable, honest proof or a clearly labeled sample, and one easy next step. Identify objections to the price and current alternatives. Draft a limited follow-up plan that stops on refusal or opt-out. Return drafts for owner review; do not send. Record real contacts and responses only after an authorized action occurs.'},
            {id:'sprint_channels',role:'outreach',title:'Build five relevant referral routes',brief:'Find five hosting operators, ASIC repair shops, generator distributors or gas-treatment firms that serve the intended buyers. Verify their service focus on original sources. Identify a credible referral reason: overflow research, customer quote comparison, territory research or early site screening. Draft a specific partnership introduction and one reciprocal benefit. Do not imply a partnership, commission agreement, customer relationship or available capacity that does not exist. Drafts only.'},
            {id:'sprint_proof',role:'analysis',title:'Prepare two small samples that prove the paid deliverable',brief:'Create one clearly labeled sample quote comparison and one supplier prospect-research sample with three evidence-linked accounts. Cap sample preparation at two hours per offer. Show what is included, source dates, assumptions and exclusions. Use the $500 review and $1,500 research pilot as unvalidated test prices. Leave complete work and delivery commitments for a scoped paid engagement. Request independent Quality Review before customer use; do not publish or send.'},
            {id:'sprint_validation',role:'revenue',title:'Review demand after ten substantive buyer conversations',brief:'Run a 14-day acquisition experiment with two offers. Working targets: 40 researched accounts, 20 qualified for outreach, ten substantive buyer conversations and two paid pilots; these are goals, not forecasts. Use actual contact and reply evidence. Compare need, timing, buyer authority, alternatives, willingness to pay, objections, delivery hours and collected contribution by service and channel. If ten conversations yield no paid pilot, revise the offer or segment before increasing volume. Report separately if the problem is low reply rate versus no willingness to pay. Arrange Quality Review of the sample and deliverables. Do not count pipeline, unearned deposits or customer equipment funds as revenue.'}
        ];
        for(var i=0;i<drafts.length;i++){
            if(!state.tasks.some(function(t){return t.id===drafts[i].id;})){
                await act('task.add',Object.assign({due:'',dealId:''},drafts[i]));
                if(view.mode==='cloud')await new Promise(function(resolve,reject){var end=Date.now()+5000;function check(){if(state.tasks.some(function(t){return t.id===drafts[i].id;}))resolve();else if(Date.now()>end)reject(new Error('Waiting for the shared register. Retry the sprint after it refreshes; saved drafts are preserved.'));else setTimeout(check,50);}check();});
            }
        }
        tab('work',false);notice('Six lead-gen sprint drafts are ready. Existing tasks were preserved. Nothing has been dispatched to Grok.');
    }
    async function launch(){
        var drafts=[
            {id:'launch_buyer_research',role:'revenue',title:'Research the first 25 qualified buyer accounts',brief:'Find miners or small operators with a specific equipment purchase, relocation or expansion signal. Prioritize ten discovery conversations. Return a source-linked account list, decision-maker routes, the pending buying decision, and personalized outreach drafts. Do not send messages.'},
            {id:'launch_supply',role:'supply',title:'Qualify hardware and hosting counterparties',brief:'Research at least two ASIC suppliers and two hosting operators relevant to North American buyers. Record published terms, current contact routes, evidence dates, and questions needed for a written quote. Treat all listed capacity as unconfirmed until supported. Draft inquiries only.'},
            {id:'launch_sample',role:'analysis',title:'Prepare a sample Proton sourcing decision packet',brief:'Create a clearly labeled demonstration of the $1,500 sourcing service: compare hardware and hosting options, delivered cost, economics, downside cases, source dates and missing information. Use explicit assumptions wherever current written quotes are absent. Do not represent the sample as a live offer.'},
            {id:'launch_review',role:'review',title:'Review the sourcing sample before customer use',brief:'Wait until the sourcing sample and supplier research are available. Independently check material evidence and calculations, identify unsupported availability or rights claims, and return pass / revise / blocked with reasons. This review does not authorize outreach or publication.'}
        ];
        // One save at a time; known IDs make this starter action repeat-safe.
        for(var i=0;i<drafts.length;i++){
            if(!state.tasks.some(function(t){return t.id===drafts[i].id;})){
                await act('task.add',Object.assign({due:'',dealId:''},drafts[i]));
                if(view.mode==='cloud')await new Promise(function(resolve){var end=Date.now()+5000;function check(){if(state.tasks.some(function(t){return t.id===drafts[i].id;})||Date.now()>end)resolve();else setTimeout(check,50);}check();});
            }
        }
        notice('Four launch drafts are ready. They have not been sent to Grok.');
    }
    function tab(name,focus){
        activeTab=name;document.querySelectorAll('[data-tab]').forEach(function(b){var selected=b.dataset.tab===name;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;$('panel-'+b.dataset.tab).hidden=!selected;});if(focus)$('tab-'+name).focus();
    }
    async function action(button){
        var a=button.dataset.action,id=button.dataset.id;
        if(a==='close')return close();if(a==='setup')return setup();if(a==='launch')return launch();if(a==='lead')return leadForm(id);if(a==='sprint')return leadSprint();
        if(a==='lead-draft'||a==='lead-deal'){var lead=(state.leads||[]).find(function(l){return l.id===id;});if(!lead||['dnc','disqualified','discovered'].includes(lead.stage))throw new Error('Research and qualify an active lead first.');return a==='lead-draft'?newTask('outreach',lead):dealForm(null,lead);}
        if(a==='signin'){if(typeof firebase==='undefined')throw new Error('Cloud sign-in could not load. Check your connection and reload; local work is preserved.');return ProtonAuthUI.show('signin');}
        if(a==='profile')return setup(id);if(a==='assign')return newTask(id);if(a==='task')return openTask(id);if(a==='deal')return dealForm(id);
        if(a==='void-cash'){
            var cashRevision=state.revision;
            modal('Correct a cash record',form('voidCashForm','<p class="ac-help">The original remains in the register, marked voided. Add a new cash entry if a replacement is needed. This does not refund or move money.</p><label>Correction reason<textarea name="reason" required maxlength="2000"></textarea></label>','Void record'));
            bindForm('voidCashForm',async function(f){await act('cash.void',{id:id,reason:f.get('reason')},cashRevision);close();notice('Record voided with its original details preserved.');});return;
        }
        if(a==='copy-task')return copy(M.packet(state,task(id),pageUrl()));
        if(a==='download-task')return download(M.packet(state,task(id),pageUrl()),'proton-'+id+'.md');
        if(a==='result')return resultForm(id);if(a==='decision')return decisionForm(id);if(a==='block')return reasonForm(id,false);if(a==='cancel')return reasonForm(id,true);
        var rev=Number(dialog.dataset.recordRevision);
        if(a==='ready'||a==='handed'||a==='start'){
            await act({'ready':'task.ready','handed':'task.handoff','start':'task.start'}[a],{id:id},rev);
            close();notice(a==='ready'?'Ready for handoff. Copy the packet into Grok, or let a connected worker claim it.':a==='handed'?'Handoff recorded from your report. This did not send a message.':'Task claimed in Proton. This records work; it does not launch Grok.');
        }
    }
    if(typeof initNav==='function')initNav('agents');
    var db=typeof firebase!=='undefined'&&firebase.apps.length?firebase.firestore():null, auth=db?firebase.auth():null;
    store=window.AgentControlStore.create({db:db,auth:auth});
    $('roleFilter').innerHTML=option('','All roles','')+roles('');$('cashMonth').value=month;
    $('leadStage').innerHTML=option('active','Active leads','active')+option('all','All leads','')+opts(M.LEAD_STAGES,'');$('leadOffer').innerHTML=option('','All services','')+opts(M.OFFERS,'');
    $('leadSearch').oninput=renderLeads;$('leadStage').onchange=renderLeads;$('leadOffer').onchange=renderLeads;$('newLeadButton').onclick=function(){leadForm();};$('leadSprintButton').onclick=function(){leadSprint().catch(error);};
    store.subscribe(function(next){var switched=lastUid!==undefined&&lastUid!==next.uid;lastUid=next.uid;view=next;state=next.state;if(switched){if(dialog.open)close();$('notice').hidden=true;}render();});
    $('newTaskButton').onclick=function(){newTask();};$('newDealButton').onclick=function(){dealForm();};$('newCashButton').onclick=cashForm;$('setupButton').onclick=function(){setup();};
    $('launchPlanButton').onclick=function(){launch().catch(error);};$('closeDialog').onclick=close;
    $('taskSearch').oninput=renderTasks;$('roleFilter').onchange=renderTasks;$('stateFilter').onchange=renderTasks;
    $('cashMonth').onchange=function(){if(/^\d{4}-\d{2}$/.test(this.value)){month=this.value;renderMetrics();renderCash();}};
    $('exportButton').onclick=function(){download(store.raw(),'proton-control-center-'+new Date().toISOString().slice(0,10)+'.json','application/json');};
    $('pauseButton').onclick=function(){var rev=state.revision;modal(state.paused?'Resume the task queue?':'Pause new task claims?',form('pauseForm','<p class="ac-prose">'+(state.paused?'Workers can claim ready tasks again. This does not start a Grok routine.':'New task claims will pause. Existing bots may still be working; send <strong>Stop now</strong> in Grok Bot to stop their current work. Results can still be recorded here.')+'</p>',state.paused?'Resume queue':'Pause queue'));bindForm('pauseForm',async function(){await act('pause',{},rev);close();});};
    $('goalButton').onclick=function(){var rev=state.revision;modal('Monthly contribution target',form('goalForm','<label>Target · USD<input name="goal" type="number" min="0.01" step="0.01" required value="'+state.goalCents/100+'"></label><p class="ac-help">After direct delivery and team costs, before owner compensation and taxes.</p>','Save target'));bindForm('goalForm',async function(f){await act('settings',{goalCents:usd(f.get('goal'))},rev);close();});};
    document.addEventListener('click',function(e){var b=e.target.closest('[data-action]');if(b)action(b).catch(error);var t=e.target.closest('[data-tab]');if(t)tab(t.dataset.tab,false);});
    document.querySelector('.ac-tabs').addEventListener('keydown',function(e){if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();var names=['leads','work','deals','cash','activity'],i=names.indexOf(activeTab);i=e.key==='Home'?0:e.key==='End'?names.length-1:(i+(e.key==='ArrowRight'?1:names.length-1))%names.length;tab(names[i],true);});
}());
