'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const I=require('../crm/intake-inbox'),S=require('../crm/sourcing-model'),A=require('../agent-control-model');
const clone=v=>JSON.parse(JSON.stringify(v));
const request=()=>({id:'REQ-12345678-1234-4234-8234-123456789012',briefRevision:1,revision:2,service:'custom_search',status:'qualified',receivedAt:'2026-09-20T12:00:00.000Z',routeEmail:'energy@protonminingco.com',queue:{state:'not_queued'},payload:{service:'custom_search',contact:{name:'Synthetic client',email:'synthetic@example.test'},brief:{power:{value:160,unit:'kW'},geography:'Pennsylvania',country:'US',sourceTypes:['grid_supply']},attribution:{source:'synthetic_test'},consent:true},history:[]});
function fixture(){
  let r=request(),state=A.initial(),s={uid:'ownerA',epoch:1,ready:true,error:'',agent:{mode:'cloud'}},failAfterWrite=false,failDispatch=false,afterToken=null,validationFailure=false;
  const calls=[],listeners=[],actions=new Map(),sites=[{id:'physical_1',name:'Synthetic site',custom_fields:{preserve:{yes:true}}}];
  const auth={currentUser:{uid:'ownerA',getIdToken:async()=>{if(afterToken)afterToken();return 'synthetic-token';}}};
  const D={status:()=>s,snapshot:()=>({uid:s.uid,epoch:s.epoch,raw:['same']}),agent:()=>state,sites:()=>sites,subscribe:fn=>listeners.push(fn),dispatch:async(type,payload,revision)=>{calls.push({kind:'dispatch',type,payload:clone(payload)});if(failDispatch)throw Error('Synthetic cloud write failure');state=A.reduce(state,{type,payload,revision,id:'event_'+state.revision,at:'2026-09-20T12:30:00.000Z'});},saveSite:async(id,patch,stamp)=>{assert.equal(stamp.epoch,s.epoch);Object.assign(sites.find(site=>site.id===id),patch);}};
  function response(body,status=200){return {ok:status>=200&&status<300,status,json:async()=>clone(body)};}
  const fetch=async(url,options)=>{calls.push({kind:'fetch',url,options:clone(options)});if(options.method==='GET'){if(url.endsWith('/metrics'))return response({receivedTotal:1,qualifiedTotal:r.status==='qualified'?1:0,queueDrafts:r.queue.state==='draft_saved'?1:0,acknowledged:r.queue.state==='acknowledged'?1:0});if(url.includes('?limit='))return response({requests:[r],nextCursor:null});return response({request:r});}
    const body=JSON.parse(options.body),prior=actions.get(body.actionId);if(validationFailure){validationFailure=false;return response({error:{code:'invalid_request',message:'Synthetic note validation failed'}},422);}if(prior){if(prior.body!==options.body)return response({error:{code:'conflict',message:'Changed retry'}},409);return response({request:r,duplicate:true});}
    if(body.expectedRevision!==r.revision)return response({error:{code:'conflict',message:'Stale record revision'}},409);
    if(body.type==='queue'){r.queue={state:'draft_saved',taskOwnerUid:'ownerA',taskId:body.taskId,briefId:body.briefId};}else if(body.type==='acknowledge')r.queue={...r.queue,state:'acknowledged',...body};else r.status=body.type==='qualify'?'qualified':'rejected';
    r.revision++;r.history.push({type:body.type,actionId:body.actionId});actions.set(body.actionId,{body:options.body});if(failAfterWrite){failAfterWrite=false;throw Error('Synthetic network disconnect after durable write');}return response({request:r,duplicate:false});};
  const inbox=I.create({D,model:S,auth,fetch,config:{endpoint:'https://private.example.test'}});inbox.select(clone(r));
  return {inbox,D,auth,calls,sites,record:()=>r,state:()=>state,change:fn=>fn(r),setValidationFailure:()=>{validationFailure=true;},setFailAfterWrite:()=>{failAfterWrite=true;},setFailDispatch:()=>{failDispatch=true;},setOffline:()=>{s.agent.mode='offline';},afterToken:fn=>{afterToken=fn;},switchAccount:()=>{s={...s,uid:'ownerB',epoch:s.epoch+1};auth.currentUser={uid:'ownerB',getIdToken:async()=> 'other-synthetic-token'};listeners.forEach(fn=>fn('account'));}};
}
test('durable task identity is independent of mutable request status revision',()=>{const r=request(),id=I.taskId(r);assert.equal(I.taskId({...r,revision:99}),id);assert.notEqual(I.taskId({...r,briefRevision:2}),id);assert(id.length<90);assert.throws(()=>I.taskId({...r,id:'../../other'}));});
test('transport validates endpoint and sends a private no-store owner-token request',async()=>{const f=fixture();await f.inbox.refresh();const c=f.calls.find(c=>c.kind==='fetch');assert.equal(c.options.headers.Authorization,'Bearer synthetic-token');assert.equal(c.options.cache,'no-store');assert.equal(c.options.credentials,'omit');assert.equal(c.options.redirect,'error');assert.equal(f.inbox.state().metrics.receivedTotal,1);assert.throws(()=>I.endpoint('https://user:password@service.example.test'));assert.throws(()=>I.endpoint('http://remote.example.test'));assert.equal(I.endpoint('http://127.0.0.1:8888/'),'http://127.0.0.1:8888');});
test('account change during token lookup prevents a request and clears previously loaded private records',async()=>{const f=fixture();await f.inbox.refresh();f.calls.length=0;f.afterToken(f.switchAccount);await assert.rejects(f.inbox.refresh(),/account changed/);assert.equal(f.calls.length,0);assert.equal(f.inbox.state().records.length,0);assert.equal(f.inbox.state().selected,null);});
test('research handoff saves one exact CRM draft before linking the queue; retry does not duplicate',async()=>{const f=fixture();await f.inbox.queue();assert.equal(f.state().tasks.length,1);const t=f.state().tasks[0];assert.equal(t.status,'draft');assert.equal(t.role,'supply');assert.match(t.brief,/Received private request: REQ-/);assert.equal(t.handoffAt,'');assert.equal(t.startedAt,'');assert.equal(f.record().queue.state,'draft_saved');const dispatch=f.calls.findIndex(c=>c.kind==='dispatch'),link=f.calls.findIndex(c=>c.kind==='fetch'&&c.options.method==='POST');assert(dispatch>=0&&link>dispatch);await f.inbox.queue();assert.equal(f.calls.filter(c=>c.kind==='dispatch').length,1);assert.equal(f.record().history.length,1);assert.equal(f.state().revision,1);assert.equal(f.state().leads.length,0);assert.equal(f.state().deals.length,0);assert.equal(f.state().entries.length,0);});
test('failed cloud save never records queue delivery and offline CRM cannot draft',async()=>{const f=fixture();f.setFailDispatch();await assert.rejects(f.inbox.queue(),/write failure/);assert.equal(f.record().queue.state,'not_queued');assert.equal(f.calls.filter(c=>c.kind==='fetch'&&c.options.method==='POST').length,0);const g=fixture();g.setOffline();await assert.rejects(g.inbox.queue(),/confirmed cloud/);assert.equal(g.calls.length,0);});
test('uncertain intake action retry uses original action ID, revision and payload once',async()=>{const f=fixture();f.setFailAfterWrite();await assert.rejects(f.inbox.mutate('qualify',{note:'Actual scope reviewed'}),/disconnect/);const saved=f.record().revision;await f.inbox.mutate('qualify',{note:'Actual scope reviewed'});const posts=f.calls.filter(c=>c.kind==='fetch'&&c.options.method==='POST');assert.equal(posts[0].options.body,posts[1].options.body);assert.equal(f.record().revision,saved);assert.equal(f.record().history.length,1);assert.match(f.inbox.state().notice,/already saved/);});
test('uncertain queue save reconciles exact linked record and does not add another task',async()=>{const f=fixture();f.setFailAfterWrite();await assert.rejects(f.inbox.queue(),/disconnect/);assert.equal(f.state().tasks.length,1);await f.inbox.queue();assert.equal(f.state().tasks.length,1);assert.equal(f.record().history.length,1);assert.match(f.inbox.state().notice,/already linked/);});
test('confirmed validation failure allows corrected values without losing the draft revision',async()=>{const f=fixture();f.setValidationFailure();await assert.rejects(f.inbox.mutate('qualify',{note:'Rejected validation value'}),/validation failed/);await f.inbox.mutate('qualify',{note:'Corrected scope note'});assert.equal(f.record().history.length,1);const posts=f.calls.filter(c=>c.kind==='fetch'&&c.options.method==='POST').map(c=>JSON.parse(c.options.body));assert.equal(posts[0].expectedRevision,posts[1].expectedRevision);assert.equal(posts[1].note,'Corrected scope note');});
test('queue reconciliation and acknowledgment cannot adopt another owner account task',async()=>{const f=fixture();await f.inbox.queue();f.change(r=>{r.queue.taskOwnerUid='ownerB';});await assert.rejects(f.inbox.queue(),/another or unrecorded CRM owner/);f.inbox.select(clone(f.record()));const posts=f.calls.filter(c=>c.kind==='fetch'&&c.options.method==='POST').length;await assert.rejects(f.inbox.mutate('acknowledge',{note:'Must not cross owners',taskId:f.record().queue.taskId,acknowledgedBy:'Synthetic actor',acknowledgedAt:'2026-09-20T12:35:00Z',evidence:'Synthetic receipt'}),/original CRM owner/);assert.equal(f.calls.filter(c=>c.kind==='fetch'&&c.options.method==='POST').length,posts);});
test('cross-tab request conflict preserves original expected revision and never writes a task',async()=>{const f=fixture();f.change(r=>{r.revision++;});await assert.rejects(f.inbox.queue(),/changed while/);assert.equal(f.state().tasks.length,0);await assert.rejects(f.inbox.mutate('qualify',{note:'Retained conflict draft'}),/Stale/);await assert.rejects(f.inbox.mutate('qualify',{note:'Retained conflict draft'}),/Stale/);const posts=f.calls.filter(c=>c.kind==='fetch'&&c.options.method==='POST');assert.equal(posts[0].options.body,posts[1].options.body);assert.equal(JSON.parse(posts[0].options.body).expectedRevision,2);});
test('supply submissions cannot create research drafts, and conflicting deterministic task text is never reused',async()=>{const f=fixture();f.change(r=>{r.service=r.payload.service='site_submission';});await assert.rejects(f.inbox.queue(),/Supply submissions/);assert.equal(f.state().tasks.length,0);const g=fixture();await g.D.dispatch('task.add',{id:I.taskId(request()),role:'supply',title:'Other work',brief:'Other work'},0);await assert.rejects(g.inbox.queue(),/different work/);assert.equal(g.record().queue.state,'not_queued');});
test('site provenance links one exact saved site without inferred authority or unrelated field loss',async()=>{const f=fixture();f.change(r=>{r.service=r.payload.service='site_submission';});f.inbox.select(clone(f.record()));await f.inbox.linkSite({siteId:'physical_1',partnerId:'synthetic_originator',partnerName:'Synthetic source',partnerKind:'referrer',originatingSource:'Private inbound',sourceReference:f.record().id,authority:'unverified',authorityEvidence:'',contactRoute:'synthetic@example.test',lastConfirmedAt:'',introductionTerms:'Unknown',recordedBy:'Synthetic Revenue'});assert.deepEqual(f.sites[0].custom_fields.preserve,{yes:true});const p=f.sites[0].custom_fields.sourcing;assert.equal(p.routes.length,1);assert.equal(p.routes[0].physicalSiteId,'physical_1');assert.equal(p.routes[0].authority,'unverified');assert.equal(p.routes[0].lastConfirmedAt,null);assert.equal(p.assessments.length,0);assert.equal(f.state().tasks.length,0);});
test('customer assessments preserve distinct unknown facets and never make a customer into a supply source',async()=>{const f=fixture();await assert.rejects(f.inbox.linkSite({siteId:'physical_1'}),/not an assumed supply contact/);await f.inbox.linkAssessment({siteId:'physical_1',recordedBy:'Synthetic Revenue',notes:'Pending exact owner and commercial evidence.',ownerInterestStatus:'unknown',termsStatus:'unknown',clientFitStatus:'unassessed'});const p=f.sites[0].custom_fields.sourcing;assert.equal(p.routes.length,0);assert.equal(p.assessments.length,1);const a=p.assessments[0];assert.equal(a.requestId,f.record().id);assert.equal(a.research.status,'not_started');assert.equal(a.ownerInterest.status,'unknown');assert.equal(a.terms.status,'unknown');assert.equal(a.clientFit.status,'unassessed');assert.deepEqual(f.sites[0].custom_fields.preserve,{yes:true});});
test('private inbox has no browser-persistent customer store or native execution',()=>{const source=fs.readFileSync(path.join(__dirname,'../crm/intake-inbox.js'),'utf8');assert.doesNotMatch(source,/localStorage|sessionStorage|indexedDB/);assert.doesNotMatch(source,/dispatch\(['"]task\.(?:ready|handoff|start)/);assert.match(source,/does not start a native bot/);});
