'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const E=require('../prospect-evidence'),U=require('../prospect-evidence-ui'),S=require('../prospect-sourcing'),Sites=require('../site-model'),Backup=require('../backup');
function setup(){const store={},uploads=[];let fail=false;global.SiteData=Sites;global.SyncEngine={save:(...a)=>uploads.push(a)};global.localStorage={getItem:k=>store[k]||null,setItem:(k,v)=>{if(fail)throw Error('Quota');store[k]=v;},key:i=>Object.keys(store)[i],get length(){return Object.keys(store).length;}};return {store,uploads,fail:v=>{fail=v;}};}
const source=()=>({by:'Test recorder',title:'Synthetic asset list',organization:'Test owner',kind:'report',source_url:'https://example.com/record',document_date:'2026-09-07',site_hint:'Exact physical identifier to verify',excerpt:'Generator replacement is required.'});
test('a single SiteData write preserves commercial, owner, relationship and capital records and enters the real backup',()=>{
 const h=setup(),fields={keep:'private',_proton_owner_confirmation_v1:{v:1,revision:0,conversations:[],actions:[],history:[]},_proton_relationship_map_v1:{v:1,revision:0,nodes:[],connections:[],history:[]},_proton_diligence_v1:{v:1,revision:0,assets:{},capacity:{},history:[]}},site=Sites.add({id:'s1',name:'Test',custom_fields:fields,quoted_rate:.03}),n=h.uploads.length;
 assert.equal(U.commit(site.id,{revision:0,type:'capture',value:source()}).ok,true);const saved=Sites.get(site.id);for(const k of Object.keys(fields))assert.deepEqual(saved.custom_fields[k],fields[k]);assert.equal(saved.quoted_rate,.03);assert.equal(saved.stage,site.stage);assert.equal(h.uploads.length,n+1);
 const exported=Backup.collect(localStorage);assert.equal(exported.protonMiningSites.sites[0].custom_fields[E.KEY].documents[0].excerpt,source().excerpt);Sites.update(site.id,{notes:'Legacy form update'});assert.equal(E.state(Sites.get(site.id)).documents.length,1);
});
test('quota failure on a linked task leaves both evidence and sourcing unchanged, with no upload',()=>{
 const h=setup(),site=Sites.add({id:'s1',name:'Test'});const commit=(revision,type,value,extra={})=>U.commit(site.id,{revision,type,value,...extra});assert.equal(commit(0,'capture',source()).ok,true);assert.equal(commit(1,'claim',{by:'Test',topic:'equipment',passage:source().excerpt,claim:'Replacement generator needed',locator:'Page 1'},{document_id:'doc_1'}).ok,true);assert.equal(commit(2,'review',{by:'Test',decision:'accepted',checked_on:'2026-09-07',source_checked:true,site_confirmed:true,match_reason:'Exact site ID',note:'Read full original'},{document_id:'doc_1',claim_id:'cl_2'}).ok,true);
 const before=JSON.stringify(Sites.get(site.id)),n=h.uploads.length;h.fail(true);const r=commit(3,'task',{by:'Test',play:'idle_generation',owner:'Test',due_on:'2026-09-10',verification:'Request replacement equipment costs'},{document_id:'doc_1',claim_id:'cl_2'});assert.equal(r.ok,false);assert.match(r.err,/draft is preserved/);assert.equal(JSON.stringify(Sites.get(site.id)),before);assert.equal(h.uploads.length,n);assert.equal(S.state(Sites.get(site.id)).signals.length,0);
});
test('untrusted titles and site names remain text in the summary; all evidence assets reach the deployment and cache',()=>{
 assert.match(U.summary({id:'s1',name:'<img onerror=x>',custom_fields:{[E.KEY]:{v:2}}}),/could not be read/);const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8'),assets=JSON.parse(read('tools/app-assets.json'));for(const f of ['prospect-evidence.js','prospect-evidence-ui.js','prospect-evidence.css']){assert.ok(assets.includes(f));assert.ok(read('sw.js').includes('./'+f));assert.ok(read('prospecting.html').includes('./'+f));}
 assert.match(read('prospect-nav.js'),/key: 'evidence'/);assert.match(read('prospect-today.js'),/!d.evidence.pending/);assert.match(read('.github/workflows/pages.yml'),/tests\/prospect-source-checks.test.js/);
});
